# Generated by Django 3.2.4 on 2021-11-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='stripe_price_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
