# Generated by Django 3.2.4 on 2021-10-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20211019_0757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciption',
            new_name='Subscription',
        ),
    ]
