# Generated by Django 3.2.4 on 2021-12-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_notification_allowed_membership'),
        ('profileusers', '0002_auto_20211201_2156'),
        ('gigs', '0002_alter_gig_allowed_membership'),
        ('checkout', '0002_auto_20211201_2156'),
        ('membership', '0002_auto_20211130_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
