# Generated by Django 3.2.4 on 2021-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_rename_subsciption_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'pre'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
