# Generated by Django 3.2.4 on 2021-10-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_membership_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='cancel_at_period_end',
        ),
    ]
