# Generated by Django 3.2.4 on 2021-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_remove_usermembership_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
