# Generated by Django 3.2.4 on 2021-11-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_usermembership_cancel_at_period_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='stripe_plan_id',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='cancel_at_period_end',
        ),
        migrations.AddField(
            model_name='membership',
            name='stripe_price_id',
            field=models.CharField(default='PRICE_ID_1', max_length=50),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(default='Free', max_length=30),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
