# Generated by Django 3.2.4 on 2021-11-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20211121_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
