# Generated by Django 3.2.4 on 2021-11-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0008_auto_20211123_2334'),
        ('gigs', '0007_alter_gig_allowed_membership'),
        ('network', '0004_alter_notification_allowed_membership'),
        ('membership', '0007_auto_20211121_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
