# Generated by Django 3.2.4 on 2021-11-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_membership_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='membership',
            name='description2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='membership',
            name='description3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='membership',
            name='description4',
            field=models.TextField(default=''),
        ),
    ]
