# Generated by Django 3.2.4 on 2021-11-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_auto_20211124_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
