# Generated by Django 3.2.4 on 2021-11-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0008_auto_20211123_2334'),
        ('network', '0003_auto_20211020_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='allowed_membership',
            field=models.ManyToManyField(to='profileusers.Membership'),
        ),
    ]
