# Generated by Django 3.2.4 on 2021-11-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20211126_1148'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLineItem',
            new_name='SubscriptionLineItem',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='membership',
        ),
        migrations.AddField(
            model_name='subscription',
            name='membership',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membership'),
        ),
    ]
