# Generated by Django 3.2.4 on 2021-12-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0002_auto_20211201_2156'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='membership',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.membership'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='profileusers.profileuser'),
        ),
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileusers.membership'),
        ),
    ]
