# Generated by Django 3.2.4 on 2021-11-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20211126_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_name',
        ),
    ]
