# Generated by Django 3.2.4 on 2021-09-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='extrainfo',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='gigdescription',
            new_name='description',
        ),
    ]
