# Generated by Django 3.2.4 on 2021-07-06 15:42

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='gig',
        ),
        migrations.AddField(
            model_name='gig',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='gig_description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='gig',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gig',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='gig',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gig',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
