# Generated by Django 3.2.5 on 2021-07-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='extrainfo',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
