# Generated by Django 3.2.4 on 2021-12-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0002_auto_20211201_2156'),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='allowed_membership',
            field=models.ManyToManyField(to='profileusers.Membership'),
        ),
    ]
