# Generated by Django 3.2.4 on 2021-07-08 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0002_auto_20210706_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='gig_description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='gig',
            name='liked',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
