# Generated by Django 3.2.4 on 2021-08-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='profession',
        ),
    ]
