# Generated by Django 3.2.5 on 2021-07-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0001_initial'),
        ('gigs', '0003_gig_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileusers.profileuser'),
        ),
    ]
