# Generated by Django 3.2.4 on 2021-08-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0006_auto_20210813_1901'),
        ('gigs', '0003_remove_gig_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='profession',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.profession'),
        ),
    ]
