# Generated by Django 3.2.4 on 2021-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('gigs', '0003_auto_20210927_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='liked',
        ),
        migrations.AddField(
            model_name='gig',
            name='allowed_membership',
            field=models.ManyToManyField(to='membership.Membership'),
        ),
    ]
