# Generated by Django 3.2.4 on 2021-07-09 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0004_auto_20210709_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='liked',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
