# Generated by Django 3.2.4 on 2021-10-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_networkusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkUsers',
        ),
    ]
