# Generated by Django 3.2.4 on 2021-07-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0016_alter_profileuser_background'),
        ('gigs', '0006_remove_gig_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.profileuser'),
        ),
    ]
