# Generated by Django 3.2.4 on 2021-07-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0016_alter_profileuser_background'),
        ('gigs', '0007_gig_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='gig',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileusers.profileuser'),
        ),
    ]
