# Generated by Django 3.2.4 on 2021-07-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_alter_gig_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='updated',
        ),
    ]
