# Generated by Django 3.2.5 on 2021-07-16 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='Profileuser',
            fields=[
                ('avatar', models.ImageField(default='profileavatar.png', upload_to='profileavatars')),
                ('background', models.ImageField(default='backgroundpic.jpg', upload_to='backgroundpics')),
                ('member_id', models.CharField(default='member_id', max_length=254, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('firstname', models.CharField(default='First Name', max_length=254)),
                ('lastname', models.CharField(default='Last Name', max_length=254)),
                ('title', models.CharField(blank=True, default=None, max_length=254)),
                ('company_name', models.CharField(blank=True, default='Company Name', max_length=254)),
                ('company_number_vat', models.CharField(blank=True, default=None, max_length=254)),
                ('description', models.TextField(max_length=250, null=True)),
                ('profession', models.CharField(default='Profession', max_length=254)),
                ('skill', models.CharField(blank=True, default=None, max_length=254)),
                ('email', models.EmailField(blank=True, default='Email', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(default='City', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
