# Generated by Django 3.2.4 on 2021-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='firstname',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='lastname',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='profession',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
