# Generated by Django 3.2.4 on 2021-08-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='company_name',
            field=models.CharField(blank=True, default='Company Name', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='firstname',
            field=models.CharField(default='First Name', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='lastname',
            field=models.CharField(default='Last Name', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='profession',
            field=models.CharField(default='Profession', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
