# Generated by Django 3.2.4 on 2021-06-30 20:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profileuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=254, null=True)),
                ('firstname', models.CharField(max_length=254)),
                ('lastname', models.CharField(max_length=254)),
                ('title', models.CharField(blank=True, max_length=254)),
                ('company_name', models.CharField(max_length=254)),
                ('company_number_vat', models.CharField(blank=True, max_length=254)),
                ('profession', models.CharField(max_length=254)),
                ('skill', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, default='profile-img.jpg', null=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.industry')),
            ],
        ),
        migrations.DeleteModel(
            name='Profileusers',
        ),
    ]
