# Generated by Django 3.2.4 on 2021-12-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('Premium', 'pre'), ('Free', 'free')], default='Free', max_length=30)),
                ('description', models.TextField(default='')),
                ('description1', models.TextField(default='')),
                ('description2', models.TextField(default='')),
                ('description3', models.TextField(default='')),
                ('description4', models.TextField(default='')),
                ('price', models.IntegerField(default=15)),
                ('stripe_price_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profileuser',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='membership',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermembership', to='profileusers.membership'),
        ),
    ]
