# Generated by Django 3.2.4 on 2021-10-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0002_termsagree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermsAgree',
        ),
    ]
