# Generated by Django 3.2.4 on 2021-07-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0002_auto_20210630_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='user_id',
            field=models.CharField(default='default', max_length=254),
            preserve_default=False,
        ),
    ]
