# Generated by Django 3.2.4 on 2021-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0002_auto_20210806_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='company_number_vat',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
