# Generated by Django 3.2.4 on 2021-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_remove_gig_profession'),
        ('profileusers', '0003_auto_20210813_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profession',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
