# Generated by Django 3.2.4 on 2021-07-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0003_profileuser_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterField(
            model_name='industry',
            name='prof_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
