# Generated by Django 3.2.4 on 2021-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('profileusers', '0004_termuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='skills',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='membership',
            field=models.ManyToManyField(to='membership.Membership'),
        ),
    ]
