# Generated by Django 3.2.4 on 2021-07-07 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileusers', '0004_auto_20210704_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='background',
            field=models.ImageField(default='profilebackground.png', upload_to='backgrounds'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
