# Generated by Django 3.2.4 on 2021-10-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0005_auto_20211009_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={},
        ),
    ]
