# Generated by Django 3.2.4 on 2021-07-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0006_alter_profileuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(default='profileavatar.png', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='background',
            field=models.ImageField(default='backgroundpic.jpg', upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.industry'),
        ),
    ]
