# Generated by Django 3.2.4 on 2021-07-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0007_auto_20210707_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='industry',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='background',
            field=models.ImageField(default='media/images/backgroundpic.jpg', upload_to='media/images'),
        ),
    ]
