# Generated by Django 3.2.4 on 2021-11-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0007_alter_profileuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(default='Free', max_length=30)),
                ('price', models.IntegerField(default=15)),
                ('stripe_price_id', models.CharField(default='PRICE_ID_1', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profileuser',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='membership',
            field=models.ManyToManyField(to='profileusers.Membership'),
        ),
    ]
