# Generated by Django 3.2.4 on 2021-07-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0008_auto_20210707_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='image',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='background',
            field=models.ImageField(default='backgroundpic.jpg', upload_to='media'),
        ),
    ]
