# Generated by Django 3.2.4 on 2021-08-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0008_matching_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matching',
            old_name='city',
            new_name='match_icity',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='country',
            new_name='match_icountry',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='industry',
            new_name='match_industry',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='profession',
            new_name='match_iprofession',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='skill',
            new_name='match_iskill',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='title',
            new_name='match_ititle',
        ),
    ]
