# Generated by Django 3.2.4 on 2021-07-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0009_auto_20210708_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(default='profileavatar.png', upload_to='profileavatars'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='background',
            field=models.ImageField(default='backgroundpic.jpg', upload_to='backgroundpics'),
        ),
    ]
