# Generated by Django 3.2.4 on 2021-08-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0010_alter_skill_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matching',
        ),
    ]
