# Generated by Django 3.2.4 on 2021-09-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0012_matching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
