# Generated by Django 3.2.4 on 2021-07-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0012_auto_20210709_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(default='profileavatar.png', upload_to='profileavatar'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='background',
            field=models.ImageField(default='backgroundpic.jpg', upload_to='backgroundpic'),
        ),
    ]
