# Generated by Django 3.2.4 on 2021-09-01 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0013_auto_20210901_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.DeleteModel(
            name='Matching',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='skills',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.skills'),
        ),
    ]
