# Generated by Django 3.2.4 on 2021-07-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0014_auto_20210709_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='background',
            field=models.ImageField(default='backgroundpic.png', upload_to='backgroundpics'),
        ),
    ]
