# Generated by Django 3.2.4 on 2021-09-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0014_auto_20210901_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='description',
            field=models.TextField(max_length=250, null=True, verbose_name='Description'),
        ),
    ]
