# Generated by Django 3.2.4 on 2021-09-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0015_alter_profileuser_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='user',
            new_name='username',
        ),
    ]
