# Generated by Django 3.2.4 on 2021-07-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0015_alter_profileuser_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='background',
            field=models.ImageField(default='backgroundpic.jpg', upload_to='backgroundpics'),
        ),
    ]
