# Generated by Django 3.2.4 on 2021-07-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0016_alter_profileuser_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={},
        ),
    ]
