# Generated by Django 3.2.4 on 2021-07-12 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0017_alter_industry_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='background',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='updated',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, default='profile-img.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.industry'),
        ),
    ]
