# Generated by Django 3.2.4 on 2021-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0018_auto_20210712_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='company_number_vat',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='title',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='username',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(default='profileavatar.png', upload_to='profileavatars'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='background',
            field=models.ImageField(default='backgroundpic.jpg', upload_to='backgroundpics'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
