# Generated by Django 3.2.4 on 2021-09-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0018_auto_20210905_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='user',
            new_name='username',
        ),
    ]
