# Generated by Django 3.2.4 on 2021-09-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0020_auto_20210915_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.business', verbose_name='Business'),
        ),
    ]
