# Generated by Django 3.2.4 on 2021-09-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0022_auto_20210915_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='business',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.business'),
        ),
    ]
