# Generated by Django 3.2.4 on 2021-09-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0023_alter_profileuser_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileusers.countries')),
            ],
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.cities'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.countries'),
        ),
    ]
