# Generated by Django 3.2.4 on 2021-09-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0026_auto_20210915_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Employment',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='countries',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='employment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.employment'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.status'),
        ),
    ]
