# Generated by Django 3.2.4 on 2021-09-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0028_auto_20210915_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='employment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.employment'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.status'),
        ),
    ]
