# Generated by Django 3.2.4 on 2021-09-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0029_auto_20210916_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='yourEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youremployment_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'yourEmployment',
            },
        ),
        migrations.CreateModel(
            name='yourStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourstatus_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'yourStatus',
            },
        ),
        migrations.AddField(
            model_name='profileuser',
            name='youremployment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.youremployment'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='yourstatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileusers.yourstatus'),
        ),
    ]
