# Generated by Django 3.2.4 on 2021-09-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0031_auto_20210917_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='youremployment',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='yourstatus',
        ),
        migrations.DeleteModel(
            name='yourEmployment',
        ),
        migrations.DeleteModel(
            name='yourStatus',
        ),
    ]
