# Generated by Django 3.2.4 on 2021-09-22 09:15

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profileusers', '0032_auto_20210917_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
